plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.26.2" # Use the latest version tag or branch
minimal_mistakes_skin: "air"

title: "Know About Me"
name: "Michael Rose"
masthead_title: "Know About Me"
read_time: true

author:
  name: "Muthu Krishnan P B"
  avatar: "/assets/images/bio-data.jpg"
  bio: "Passionate Software Engineer and an Expert in Building Robust and Efficient Applications"
  location: "Chennai, India"
  links:
    - label: "Leetcode"
      icon: "/assets/images/lc.png"
      url: "https://leetcode.com/u/muthukrishnanpb/"
    - label: "Linked In"
      icon: "/assets/images/linkedin.png"
      url: "https://www.linkedin.com/in/muthu-krishnan-p-b-65a2b057/"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"