theme: minimal-mistakes-jekyll
title: Your Site Title
description: A description of your site.
url: "https://muthukrishnanpb.github.io"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
