plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.26.2" # Use the latest version tag or branch
minimal_mistakes_skin: "air"

title: "Profile - Muthu Krishnan P B"
masthead_title: "Read My Story"

author:
  name: "Muthu Krishnan P B"
  avatar: "/assets/images/bio-data.jpg"
  bio: "Passionate Software Engineer and an Expert in Building Robust and Efficient Applications"
  location: "Chennai, India"
  links:
    - label: "Linked In"
      icon: "/assets/images/linkedin.jpg"
      url: "https://www.linkedin.com/in/muthu-krishnan-p-b-65a2b057/"
    - label: "Leetcode"
      icon: "/assets/images/lc.jpg"
      url: "https://leetcode.com/u/muthukrishnanpb/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: foo
    values:
      layout: single
