title: Your Site Title
description: A description of your site.
url: "https://username.github.io" # Update with your GitHub Pages URL

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.26.0" # Use the latest version tag or branch

